### ISSUE TITLE
IIIF AnnotationLists should be framed to generate expected serialization

### ISSUE THREAD

**Issue by azaroth42** [sul-dlss/triannon#155]
The Annotation Lists from solr (through Triannon) should be framed with either 
http://iiif.io/api/presentation/2/annotation_frame.json
or 
http://iiif.io/api/presentation/2/annotationList_frame.json
as appropriate to ensure that the representation is what is expected by Mirador and other IIIF clients.

Example in JSON-LD playground of framing:
http://tinyurl.com/mn3orqp

**Comment by azaroth42** [comment]
Sub-issue of #127

**Comment by ndushay** [comment]
![untitled](https://cloud.githubusercontent.com/assets/96775/6975942/bc06f544-d957-11e4-967e-66deade4b5c7.png)

**Comment by ndushay** [comment]
On 4/2/15 9:14 AM, Rob Sanderson wrote:

Hi Naomi,

A couple of fixes:

1. Can you drop the @graph nodes from the list?

So instead of 
    resources: [{@graph: [{@id: ... }]}]
It would just be
    resources: [{@id:...}]

2.  Can you nest the body underneath the "resource" key?

So:  {"@id":"...", "@type": "oa:Annotation", "resource": {"@type": [dctypes:Text], "chars":""}}

I think that Mirador would then be okay with the response.
At the very least the _:b0s would need to be made to be unique... and if you're messing with the ids anyway, the nested structure is better.

Thanks!

Rob

**Comment by ndushay** [comment]
![untitled 2](https://cloud.githubusercontent.com/assets/96775/6975958/e58cc0e2-d957-11e4-8749-9c0266edc61b.png)

**Comment by ndushay** [comment]
commit 0381caf addresses this

**Comment by ndushay** [comment]
closed with #157  (and gem release 0.7.0)
